name: cdktf-diff
description: Execute cdktf diff, parse STDOUT/STDERR output, and return outputs based on the outcomes.
inputs:
  github_token:
    description: GITHUB_TOKEN to use GitHub API. Simply specify secrets.GITHUB_TOKEN.
    required: true
  job_name:
    description: jobs.<job-id>.name of this workflow job. This is needed to get the job ID via query.
    required: true
  output_filename:
    description: Name of the file this jobs outputs will be saved into.
    required: true
  ref:
    description: The ref (branch or sha) to use with the diff.
    required: true
  stack:
    description: Full name of the CDKTF stack to diff.
    required: true
  stub_output_file:
    description: When present, no Terraform will execute. The output of this action will be substituted with the output contained in this file. This is useful for cases when you want to test but don't have authentication set up.
  terraform_version:
    default: 1.8.0
    description: The version of Terraform to use
  working_directory:
    default: ./
    description: Working directory path that contains your cdktf code.
  skip_synth:
    default: false
    description: Skip synthesis of the application, assume the synthesized Terraform code is already present and up to date
  artifact_name:
    description: When given, attempt to download the given artifact contents into this working directory.
outputs:
  html_url:
    description: Direct link to this job, which shows the full execution output.
    value: ${{ steps.jobid_action.outputs.html_url }}
  job_id:
    description: ID of this job
    value: ${{ steps.jobid_action.outputs.job_id }}
  result_code:
    description: Similar to exitcode behavior for Terraform, not yet supported by CDKTF.  0 = Succeeded with empty diff (no changes), 1 = Error, 2 = Succeeded with non-empty diff (changes present)
    value: ${{ steps.diff.outputs.result_code }}
  stack:
    description: Full name of the CDKTF stack used for the diff.
    value: ${{ inputs.stack }}
  summary:
    description: Single string of output to summarize the results.
    value: ${{ steps.diff.outputs.summary }}

runs:
  using: composite
  steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - uses: actions/checkout@v4
      id: checkout
      with:
        fetch-depth: 0
        ref: ${{ inputs.ref }}

    - name: Load Configuration
      id: configurations
      shell: bash
      run: |
        cd ${{ inputs.working_directory }}
        echo "node_version=$(cat .nvmrc)" >> $GITHUB_OUTPUT

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.configurations.outputs.node_version }}

    - name: Install Node Dependencies
      shell: bash
      run: |
        cd ${{ inputs.working_directory }}
        npm ci

    - name: Download Artifact Files
      if: ${{ inputs.artifact_name }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.working_directory }}/cdktf.out

    - name: Run Diff Action
      id: diff_action
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_JOB_NAME: ${{ inputs.job_name }}
        INPUT_OUTPUT_FILENAME: ${{ inputs.output_filename }}
        INPUT_REF: ${{ inputs.ref }}
        INPUT_STACK: ${{ inputs.stack }}
        INPUT_STUB_OUTPUT_FILE: ${{ inputs.stub_output_file }}
        INPUT_TERRAFORM_VERSION: ${{ inputs.terraform_version }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working_directory }}
        INPUT_SKIP_SYNTH: ${{ inputs.skip_synth }}
        INPUT_ARTIFACT_NAME: ${{ inputs.artifact_name }}
      run: node ${{ github.action_path }}/dist/index.js

    - uses: actions/upload-artifact@v4
      name: Save Outputs
      with:
        name: ${{ steps.diff_action.outputs.jobId }}
        path: ${{ inputs.working_directory }}/${{ inputs.output_filename }}
